# This is a travis-ci.org continuous integration configuration file.
language: c

addons:
  apt:
    packages:
      # AVR GCC packages
      - gcc-avr
      - avr-libc
      # PRU GCC build packages
      - pv
      - libmpfr-dev
      - libgmp-dev
      - libmpc-dev
      - texinfo
      - libncurses5-dev
      - bison
      - flex

cache:
  directories:
  - travis_cache

install: ./scripts/travis-install.sh

script: ./scripts/travis-build.sh
